### ISSUE TITLE
Сомнительное решение data-state

### ISSUE THREAD

**Issue by retyui** [andrew--r/ui-developer-tips#3]
Несколько вопросов по [data-state](https://github.com/andrew--r/ui-developer-tips/tree/master/tips/009-data-state)

Не понимаю зачем хранить   `dataStates` вне `comments`?
Ах наверное что бы делать лишние тело движения  `comments.dataState = dataStates.loading;`
Реализацию лучше скрыть внутри `comments `, думаю следующий код откроет вам глаза где слабое место в вашем примере.
```js
const comments = (dataStates => {
    const hiddenVar = {
        dataState: dataStates.notAsked,
        errorText: '',
        data: [],
    };

    return {
        set data(val) {
            hiddenVar.dataState = dataStates.loaded; // 🔥
            hiddenVar.data = val
        },
        get data() {
            return hiddenVar.data.slice(0);
        },

        set errorText(val) {
            hiddenVar.dataState = dataStates.failed; // 🔥
            hiddenVar.errorText = val;
        },
        get errorText() {
            return hiddenVar.errorText;
        },

        set loading(val) {
            if(val){
                hiddenVar.dataState = dataStates.loading; // 🔥
            }
        },

        get isLoading() {
            return hiddenVar.dataState === dataStates.loading;
        },
        get isLoaded() {
            return hiddenVar.dataState === dataStates.loaded;
        },
        get isError() {
            return hiddenVar.dataState === dataStates.failed;
        }
    }
})({
    notAsked: 'notAsked',
    loading: 'loading',
    loaded: 'loaded',
    failed: 'failed',
});



 // Более лаконичный вариант 
 function loadComments() {
     comments.loading = true;
     fetch('/comments').then((response)=>response.json()).then((data)=>{
         comments.data = data;
     }).catch((error)=>{
         comments.errorText = error.message;
     });
 }

```
покуда нет `private` свойств вынес в отдельный объект `hiddenVar `  скрытые переменные.
заменить значения `dataStates ` на числа 
можно пойти дальше и добавить в реализацию `onChange` что бы при изменении `hiddenVar.dataState` вызывались слушатели(listeners) этого объекта `comments`

**Comment by fletcherist** [comment]
Мне кажется, что под `dataStates`  Андрей имел в виду просто константу состояний компонента, не обязательно комментов, поэтому вынос вне функции вполне оправдан. А вот эта сеттерная магия мне уже кажется запутывающей.

**Comment by retyui** [comment]
@fletcherist `dataStates` как это как набор флагов с помощью которых мы из вне сможем переключать состояние `comments`
Только вот беда наша функция `loadComments` зависит уже от двух внешних переменных

![image](https://user-images.githubusercontent.com/4661784/33891176-35028410-df66-11e7-83a8-756d82120ee7.png)

Эта сеттерная магия как V2.0 этого кривого решения

**Comment by andrew--r** [comment]
@retyui главной целью заметки было показать, что состояние данных можно выразить одним полем, а не несколькими флагами. Код в примерах максимально упрощён и непригоден для использования в продакшене по многим причинам, он служит лишь иллюстрацией принципа. Вероятно, стоит отдельно указать это в заметке.

**Comment by andrew--r** [comment]
Добавил в совет дисклеймер о том, что код максимально упрощён в угоду иллюстрации основной идеи.
