### ISSUE TITLE
Убрать "noreferrer". Достаточно одного "noopener"

### ISSUE THREAD

**Issue by pongo** [andrew--r/ui-developer-tips#4]
В совете про [target blank](https://github.com/andrew--r/ui-developer-tips/tree/master/tips/001-target-blank) достаточно указать `rel="noopener"`. Проблему безопасности это решает.

`noreferrer` лучше не добавлять, потому что это будет ломать статистику переходов (для сайта, на который стоит ссылка). Системы аналитики будут думать, что посетители пришли не с какого-то сайта, а набрали адрес вручную (или перешли из приложения и т.п.)

**Comment by andrew--r** [comment]
Привет!

Спасибо за замечание, я дополнил совет:

> Ссылка на глобальный объект родительской вкладки лежит в window.opener. noopener в атрибуте rel принудительно обнуляет значение window.opener для открываемых вкладок; это работает с 49 версии Хрома и 36 версии Оперы. Для более старых браузеров нужно добавлять noreferrer — это обнуляет тоже обнуляет window.opener, но также предотвращает отправку заголовка Referer (это может негативно сказаться на сборе статистики переходов).
