### ISSUE TITLE
readme.md file issue 

### ISSUE THREAD

**Issue by kasiriveni** [andrew--r/ui-developer-tips#5]
Currently, the user must click the **readme.md** file manually .if you follow the naming as **README.md** its resolve the issue

**Comment by andrew--r** [comment]
Hello! Sorry, didn't get the issue right. I use the desktop web version of GitHub and I when I open any folder with `readme.md` I see it immediately and I don't have to click it manually. What GitHub client do you use?

**Comment by kasiriveni** [comment]
i open in mobile

**Comment by andrew--r** [comment]
Ok, I renamed `readme.md` to `README.md` at https://github.com/andrew--r/ui-developer-tips/tree/master/tips/001-target-blank and the behaviour on mobile version didn't change:

<img width="369" alt="screen shot 2018-03-02 at 18 34 53" src="https://user-images.githubusercontent.com/2734841/36907048-94acbfcc-1e48-11e8-970f-5cfd9f340cbb.png">

So I suppose it's not a bug, but a feature of github's mobile version :–)
