### ISSUE TITLE
Совет про URL.createObjectURL

### ISSUE THREAD

**Issue by inoyakaigor** [andrew--r/ui-developer-tips#8]
Рекомендация к использованию синхронного метода для работы с такими жирными данными как изображения да ещё с необходимостью руками чистить память вместо асинхронного и более простого выглядит как начало новой книги Вредных советов Григория Остера.

Есть ли пруфы, что так лучше? Бенчмарки там, ещё что-нибудь?

**Comment by andrew--r** [comment]
Привет! Спасибо за вопрос, действительно, этой информации не хватало.

Расширил заметку объяснением о том, почему `URL.createObjectURL` лучше и производительнее, и добавил ссылку на секцию в спецификации с описанием алгоритма генерации URL для блобов: https://github.com/forwebdev/ui-developer-tips/commit/5985f93230ab5262adbf3eafed6dc1dbf6ce3a93
